name: Build and Deploy Next.js + Docs

on:
  push:
    branches: ['main', 'feature/**']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ... existing steps to install node deps and run next build ...
      - name: Install Node dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # --- MkDocs build step: build docs into `site/` ---
      - name: Set up Python (for MkDocs)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs + Material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-redirects mkdocs-minify-plugin

      - name: Build MkDocs site
        run: mkdocs build --clean

      # --- Copy docs into Next.js static export directory (so artifact contains docs) ---
      - name: Ensure out directory exists
        run: mkdir -p out

      # If you already run `next export` to create out/, copy docs into out/docs
      - name: Copy docs into artifact
        run: |
          # Put docs under /docs in the artifact
          mkdir -p out/docs
          cp -a site/. out/docs/

      # Continue with your artifact upload step (actions/upload-pages-artifact or next export)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
